## · Dimensionality Reduction

### · Priciple Component Analysis (PCA)

In [680]:
#Let's import libraries
import pandas as pd
import warnings as wg
wg.filterwarnings('ignore')

In [681]:
#Let's enter path 
path = "small - small.csv"
df = pd.read_csv(path)

In [682]:
#Data Frame
df

,rev_Mean,mou_Mean,totmrc_Mean,da_Mean,ovrmou_Mean,ovrrev_Mean,vceovr_Mean,datovr_Mean,roam_Mean,change_mou,...,forgntvl,ethnic,kid0_2,kid3_5,kid6_10,kid11_15,kid16_17,creditcd,eqpdays,Customer_ID
0,24,219,22,0,0,0,0,0,0,-157,...,0,N,U,U,U,U,U,Y,361,1000001
1,55,570,72,0,0,0,0,0,0,38,...,0,I,U,U,U,U,U,Y,434,1000005
2,32,26,30,0,0,0,0,0,0,60,...,1,N,U,U,U,U,U,Y,601,1000010
3,213,1972,85,2,250,100,100,0,36,-200,...,0,N,U,U,Y,U,U,Y,199,1000015
4,63,440,60,0,6,2,2,0,1,-16,...,0,N,U,U,U,U,U,Y,530,1000017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,64,258,70,2,0,0,0,0,2,128,...,0,N,U,U,U,U,U,Y,334,1004986
1420,31,164,30,0,0,0,0,0,1,-70,...,0,N,U,U,U,U,U,Y,1162,1004988
1421,48,263,58,0,0,0,0,0,0,38,...,1,H,U,U,Y,Y,U,Y,374,1004990
1422,20,3,20,0,0,0,0,0,0,-1,...,0,U,U,U,U,U,U,Y,1054,1004998
1423,50,202,60,0,0,0,0,0,0,-57,...,0,N,Y,Y,U,U,U,Y,592,1005000

In [683]:
#Let's look at columns
df.columns

Index(['rev_Mean', 'mou_Mean', 'totmrc_Mean', 'da_Mean', 'ovrmou_Mean',
       'ovrrev_Mean', 'vceovr_Mean', 'datovr_Mean', 'roam_Mean', 'change_mou',
       'change_rev', 'drop_vce_Mean', 'drop_dat_Mean', 'blck_vce_Mean',
       'blck_dat_Mean', 'unan_vce_Mean', 'unan_dat_Mean', 'plcd_vce_Mean',
       'plcd_dat_Mean', 'recv_vce_Mean', 'recv_sms_Mean', 'comp_vce_Mean',
       'comp_dat_Mean', 'custcare_Mean', 'ccrndmou_Mean', 'cc_mou_Mean',
       'inonemin_Mean', 'threeway_Mean', 'mou_cvce_Mean', 'mou_cdat_Mean',
       'mou_rvce_Mean', 'owylis_vce_Mean', 'mouowylisv_Mean',
       'iwylis_vce_Mean', 'mouiwylisv_Mean', 'peak_vce_Mean', 'peak_dat_Mean',
       'mou_peav_Mean', 'mou_pead_Mean', 'opk_vce_Mean', 'opk_dat_Mean',
       'mou_opkv_Mean', 'mou_opkd_Mean', 'drop_blk_Mean', 'attempt_Mean',
       'complete_Mean', 'callfwdv_Mean', 'callwait_Mean', 'churn', 'months',
       'uniqsubs', 'actvsubs', 'new_cell', 'crclscod', 'asl_flag', 'totcalls',
       'totmou', 'totrev', 'adjrev', 'adjmou', 'adjqty', 'avgrev', 'avgmou',
       'avgqty', 'avg3mou', 'avg3qty', 'avg3rev', 'avg6mou', 'avg6qty',
       'avg6rev', 'prizm_social_one', 'area', 'dualband', 'refurb_new',
       'hnd_price', 'phones', 'models', 'hnd_webcap', 'truck', 'rv', 'ownrent',
       'lor', 'dwlltype', 'marital', 'adults', 'infobase', 'income',
       'numbcars', 'HHstatin', 'dwllsize', 'forgntvl', 'ethnic', 'kid0_2',
       'kid3_5', 'kid6_10', 'kid11_15', 'kid16_17', 'creditcd', 'eqpdays',
       'Customer_ID'],
      dtype='object')

In [684]:
#Let's examine info of Data Frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1424 entries, 0 to 1423
Data columns (total 100 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   rev_Mean          1424 non-null   int64
 1   mou_Mean          1424 non-null   int64
 2   totmrc_Mean       1424 non-null   int64
 3   da_Mean           1424 non-null   int64
 4   ovrmou_Mean       1424 non-null   int64
 5   ovrrev_Mean       1424 non-null   int64
 6   vceovr_Mean       1424 non-null   int64
 7   datovr_Mean       1424 non-null   int64
 8   roam_Mean         1424 non-null   int64
 9   change_mou        1424 non-null   int64
 10  change_rev        1424 non-null   int64
 11  drop_vce_Mean     1424 non-null   int64
 12  drop_dat_Mean     1424 non-null   int64
 13  blck_vce_Mean     1424 non-null   int64
 14  blck_dat_Mean     1424 non-null   int64
 15  unan_vce_Mean     1424 non-null   int64
 16  unan_dat_Mean     1424 non-null   int64
 17  plcd_vce_Mean     1424 non-null   int64
 18  plcd_dat_Mean     1424 non-null   int64
 19  recv_vce_Mean     1424 non-null   int64
 20  recv_sms_Mean     1424 non-null   int64
 21  comp_vce_Mean     1424 non-null   int64
 22  comp_dat_Mean     1424 non-null   int64
 23  custcare_Mean     1424 non-null   int64
 24  ccrndmou_Mean     1424 non-null   int64
 25  cc_mou_Mean       1424 non-null   int64
 26  inonemin_Mean     1424 non-null   int64
 27  threeway_Mean     1424 non-null   int64
 28  mou_cvce_Mean     1424 non-null   int64
 29  mou_cdat_Mean     1424 non-null   int64
 30  mou_rvce_Mean     1424 non-null   int64
 31  owylis_vce_Mean   1424 non-null   int64
 32  mouowylisv_Mean   1424 non-null   int64
 33  iwylis_vce_Mean   1424 non-null   int64
 34  mouiwylisv_Mean   1424 non-null   int64
 35  peak_vce_Mean     1424 non-null   int64
 36  peak_dat_Mean     1424 non-null   int64
 37  mou_peav_Mean     1424 non-null   int64
 38  mou_pead_Mean     1424 non-null   int64
 39  opk_vce_Mean      1424 non-null   int64
 40  opk_dat_Mean      1424 non-null   int64
 41  mou_opkv_Mean     1424 non-null   int64
 42  mou_opkd_Mean     1424 non-null   int64
 43  drop_blk_Mean     1424 non-null   int64
 44  attempt_Mean      1424 non-null   int64
 45  complete_Mean     1424 non-null   int64
 46  callfwdv_Mean     1424 non-null   int64
 47  callwait_Mean     1424 non-null   int64
 48  churn             1424 non-null   int64
 49  months            1424 non-null   int64
 50  uniqsubs          1424 non-null   int64
 51  actvsubs          1424 non-null   int64
 52  new_cell          1424 non-null   object
 53  crclscod          1424 non-null   object
 54  asl_flag          1424 non-null   object
 55  totcalls          1424 non-null   int64
 56  totmou            1424 non-null   int64
 57  totrev            1424 non-null   int64
 58  adjrev            1424 non-null   int64
 59  adjmou            1424 non-null   int64
 60  adjqty            1424 non-null   int64
 61  avgrev            1424 non-null   int64
 62  avgmou            1424 non-null   int64
 63  avgqty            1424 non-null   int64
 64  avg3mou           1424 non-null   int64
 65  avg3qty           1424 non-null   int64
 66  avg3rev           1424 non-null   int64
 67  avg6mou           1424 non-null   int64
 68  avg6qty           1424 non-null   int64
 69  avg6rev           1424 non-null   int64
 70  prizm_social_one  1424 non-null   object
 71  area              1424 non-null   object
 72  dualband          1424 non-null   object
 73  refurb_new        1424 non-null   object
 74  hnd_price         1424 non-null   int64
 75  phones            1424 non-null   int64
 76  models            1424 non-null   int64
 77  hnd_webcap        1424 non-null   object
 78  truck             1424 non-null   int64
 79  rv                1424 non-null   int64
 80  ownrent           1424 non-null   object
 81  lor               1424 non-null   int64
 82  dwlltype          1424 non-null   object
 83  marital           1424 non-null   object
 84  adults            1424 non-null   int64
 85  infobase          1424 non-null   object
 86  income            1424 non-null   int64
 87  numbcars          1424 non-null   int64
 88  HHstatin          1424 non-null   object
 89  dwllsize          1424 non-null   object
 90  forgntvl          1424 non-null   int64
 91  ethnic            1424 non-null   object
 92  kid0_2            1424 non-null   object
 93  kid3_5            1424 non-null   object
 94  kid6_10           1424 non-null   object
 95  kid11_15          1424 non-null   object
 96  kid16_17          1424 non-null   object
 97  creditcd          1424 non-null   object
 98  eqpdays           1424 non-null   int64
 99  Customer_ID       1424 non-null   int64
dtypes: int64(79), object(21)
memory usage: 1.1+ MB

In [685]:
#Description of Data Frame
df.describe().T

,count,mean,std,min,25%,50%,75%,max
rev_Mean,1424.0,6.587570e+01,48.316180,5.0,35.00,52.0,82.00,530.0
mou_Mean,1424.0,5.695449e+02,610.472017,0.0,165.00,381.5,767.75,5863.0
totmrc_Mean,1424.0,5.094382e+01,30.088596,5.0,30.00,45.0,66.00,302.0
da_Mean,1424.0,1.134831e+00,3.060426,0.0,0.00,0.0,1.00,55.0
ovrmou_Mean,1424.0,5.077107e+01,132.565929,0.0,0.00,2.0,42.00,1949.0
...,...,...,...,...,...,...,...,...
income,1424.0,6.179775e+00,2.101764,1.0,5.00,6.0,8.00,9.0
numbcars,1424.0,1.542837e+00,0.629218,1.0,1.00,1.0,2.00,3.0
forgntvl,1424.0,1.116573e-01,0.315055,0.0,0.00,0.0,0.00,1.0
eqpdays,1424.0,4.543048e+02,343.091486,0.0,185.75,377.0,636.25,1406.0
Customer_ID,1424.0,1.002415e+06,1489.027118,1000001.0,1001058.75,1002372.5,1003734.75,1005000.0

In [686]:
#Shape of Data Frame (rows , columns)
df.shape

(1424, 100)

In [687]:
#Let's create new dataframe and useless columns add those to data frame
#Data frame not useless
df_nu = pd.DataFrame()

### 1) Columns which number of unique values is [0 , 1] or greater than 70% length of original data frame

In [688]:
#Let's add
for i,v in zip(df.nunique().index , df.nunique()):
    if v in [0,1] or v > 1000:
       df_nu[i] = df[i]

In [689]:
#Let's look at data frame
df_nu

      totcalls  totmou  totrev  adjrev  adjmou  adjqty infobase  Customer_ID
0         1652    4228    1505    1453    4085    1602        M      1000001
1         4485   14028    2181    2166   13965    4452        M      1000005
2          391     994    1458    1458     976     377        M      1000010
3        33184   69161    6617    6573   69104   33139        M      1000015
4         4078   11330    1739    1723   11316    4067        M      1000017
...        ...     ...     ...     ...     ...     ...      ...          ...
1419      1649    4578    1237    1202    4546    1637        M      1004986
1420      1852    7907    1064    1002    7891    1844        M      1004988
1421      3940   13479    2207    2133   13261    3888        M      1004990
1422       243    1035     995     950    1035     243        M      1004998
1423     10143   38688    5850    5808   38601   10097        M      1005000

[1424 rows x 8 columns]

In [690]:
#Let's find columns which we add as useless columns
useless = list(df_nu.columns)

## 2) Columns which have imbalance problems

In [691]:
#Let's look at imbalanced features
for i,v in zip(df.nunique().index , df.nunique()):
    if v == 2:
        if df[i].value_counts()[1] < df[i].value_counts()[0]*0.04:
            print(df[i].value_counts())
            if i not in useless:
                useless.append([i])
            print('=============================')

N    1407
Y      17
Name: asl_flag, dtype: int64
=============================
O    1397
R      27
Name: ownrent, dtype: int64
=============================
Y    1381
N      43
Name: creditcd, dtype: int64
=============================

In [692]:
#List which contain Useless columns
useless

['totcalls',
 'totmou',
 'totrev',
 'adjrev',
 'adjmou',
 'adjqty',
 'infobase',
 'Customer_ID',
 ['asl_flag'],
 ['ownrent'],
 ['creditcd']]

## 3) Columns which have low correllation with churn column

In [693]:
#Let's look at correlations of columns with target columns 
for i in df.select_dtypes('int').columns:
    corr = df[i].corr(df['churn'])
    if abs(corr) < 0.02:
        if i not in useless:
            useless.append(i)
        print(f'{i} & Churn ==> ,Correlation: {corr}')

da_Mean & Churn ==> ,Correlation: -0.013677310522507055
ovrmou_Mean & Churn ==> ,Correlation: 0.015952725408881402
ovrrev_Mean & Churn ==> ,Correlation: 0.010799699939838828
vceovr_Mean & Churn ==> ,Correlation: 0.01184754118893394
drop_vce_Mean & Churn ==> ,Correlation: 0.012382930093257138
drop_dat_Mean & Churn ==> ,Correlation: 0.016206744247894637
blck_dat_Mean & Churn ==> ,Correlation: -0.016088215481165836
unan_vce_Mean & Churn ==> ,Correlation: -0.004186870321162192
plcd_dat_Mean & Churn ==> ,Correlation: 0.0030980941996972223
comp_dat_Mean & Churn ==> ,Correlation: 0.00545966377889775
ccrndmou_Mean & Churn ==> ,Correlation: 0.014496614338728488
mou_cdat_Mean & Churn ==> ,Correlation: 0.0018523491306957746
iwylis_vce_Mean & Churn ==> ,Correlation: -0.019192476522889832
peak_dat_Mean & Churn ==> ,Correlation: 0.004266050558975692
mou_pead_Mean & Churn ==> ,Correlation: -0.006165759173570407
opk_dat_Mean & Churn ==> ,Correlation: 0.005795170693261576
mou_opkd_Mean & Churn ==> ,Correlation: 0.009258178460152722
callfwdv_Mean & Churn ==> ,Correlation: -0.012412527971007857
callwait_Mean & Churn ==> ,Correlation: -0.007511537193879426
months & Churn ==> ,Correlation: -0.017507460578212466
uniqsubs & Churn ==> ,Correlation: -0.016511354602597384
totcalls & Churn ==> ,Correlation: -0.012230441153323618
totmou & Churn ==> ,Correlation: -0.01638932878937797
adjmou & Churn ==> ,Correlation: -0.016680468078599724
adjqty & Churn ==> ,Correlation: -0.01260836501588577
avgmou & Churn ==> ,Correlation: -0.016536398629018293
avgqty & Churn ==> ,Correlation: -0.01234153895858222
phones & Churn ==> ,Correlation: -0.004645437658572896
rv & Churn ==> ,Correlation: 0.0037804879482559186
income & Churn ==> ,Correlation: -0.00010577456485728162
forgntvl & Churn ==> ,Correlation: -0.008533748035161232
Customer_ID & Churn ==> ,Correlation: 0.009903556629457855

In [694]:
#Let's normalize columns
for i in df.select_dtypes('int'):
    df[i] = (df[i] - df[i].min())/(df[i].max() - df[i].min())

In [695]:
#Let's encode categorical columns
from sklearn.preprocessing import LabelEncoder
for i in df.select_dtypes(exclude = ['int','float']).columns:
    df[i] = LabelEncoder().fit_transform(df[i])

In [696]:
#Let's check general number of columns
len(useless)

38

In [697]:
#Let's examine null values
for i in df.isnull().sum():
    if i>1:
        print(i)

In [698]:
#Data Frame
df

,rev_Mean,mou_Mean,totmrc_Mean,da_Mean,ovrmou_Mean,ovrrev_Mean,vceovr_Mean,datovr_Mean,roam_Mean,change_mou,...,forgntvl,ethnic,kid0_2,kid3_5,kid6_10,kid11_15,kid16_17,creditcd,eqpdays,Customer_ID
0,0.036190,0.037353,0.057239,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.538402,...,0.0,8,0,0,0,0,0,1,0.256757,0.000000
1,0.095238,0.097220,0.225589,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.588829,...,0.0,5,0,0,0,0,0,1,0.308677,0.000800
2,0.051429,0.004435,0.084175,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.594518,...,1.0,8,0,0,0,0,0,1,0.427454,0.001800
3,0.396190,0.336347,0.269360,0.036364,0.128271,0.465116,0.465116,0.0,0.352941,0.527282,...,0.0,8,0,0,1,0,0,1,0.141536,0.002801
4,0.110476,0.075047,0.185185,0.000000,0.003079,0.009302,0.009302,0.0,0.009804,0.574864,...,0.0,8,0,0,0,0,0,1,0.376956,0.003201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,0.112381,0.044005,0.218855,0.036364,0.000000,0.000000,0.000000,0.0,0.019608,0.612102,...,0.0,8,0,0,0,0,0,1,0.237553,0.997199
1420,0.049524,0.027972,0.084175,0.000000,0.000000,0.000000,0.000000,0.0,0.009804,0.560900,...,0.0,8,0,0,0,0,0,1,0.826458,0.997600
1421,0.081905,0.044858,0.178451,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.588829,...,1.0,4,0,0,1,1,0,1,0.266003,0.998000
1422,0.028571,0.000512,0.050505,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.578743,...,0.0,13,0,0,0,0,0,1,0.749644,0.999600
1423,0.085714,0.034453,0.185185,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.564262,...,0.0,8,1,1,0,0,0,1,0.421053,1.000000

In [699]:
#Let's create data frame containing with useless columns
for i in useless:
    df_nu[i] = df[i]

In [700]:
df_target = df['churn']
del df['churn']

In [701]:
#Let's import PCA library  
from sklearn.decomposition import PCA

In [702]:
#Let's fit df to PCA
pca = PCA(n_components = 1).fit(df_nu)

In [703]:
#Let's examine what the optimal number of components is 
n_components = 1
while pca.explained_variance_ratio_.cumsum()[-1] < 0.95:
    pca = PCA(n_components = n_components).fit(df_nu)
    print(f'Components ==> {n_components} : {pca.explained_variance_ratio_.cumsum()}')
    print("======================================================================================")
    n_components += 1

Components ==> 1 : [0.2422426]
======================================================================================
Components ==> 2 : [0.2422426  0.45726293]
======================================================================================
Components ==> 3 : [0.2422426  0.45726293 0.58244656]
======================================================================================
Components ==> 4 : [0.2422426  0.45726293 0.58244656 0.68630174]
======================================================================================
Components ==> 5 : [0.2422426  0.45726293 0.58244656 0.68630174 0.76899937]
======================================================================================
Components ==> 6 : [0.2422426  0.45726293 0.58244656 0.68630174 0.76899937 0.80605308]
======================================================================================
Components ==> 7 : [0.2422426  0.45726293 0.58244656 0.68630174 0.76899937 0.80605308
 0.84189427]
======================================================================================
Components ==> 8 : [0.2422426  0.45726293 0.58244656 0.68630174 0.76899937 0.80605308
 0.84189428 0.87037966]
======================================================================================
Components ==> 9 : [0.2422426  0.45726293 0.58244656 0.68630174 0.76899937 0.80605308
 0.84189428 0.87037966 0.89321161]
======================================================================================
Components ==> 10 : [0.2422426  0.45726293 0.58244656 0.68630174 0.76899937 0.80605308
 0.84189428 0.87037966 0.89321161 0.91226037]
======================================================================================
Components ==> 11 : [0.2422426  0.45726293 0.58244656 0.68630174 0.76899937 0.80605308
 0.84189428 0.87037966 0.89321161 0.91226037 0.92654416]
======================================================================================
Components ==> 12 : [0.2422426  0.45726293 0.58244656 0.68630174 0.76899937 0.80605308
 0.84189428 0.87037966 0.89321161 0.91226037 0.92654416 0.93945353]
======================================================================================
Components ==> 13 : [0.2422426  0.45726293 0.58244656 0.68630174 0.76899937 0.80605308
 0.84189428 0.87037966 0.89321161 0.91226037 0.92654416 0.93945353
 0.95023576]
======================================================================================

In [704]:
#Let's fit df to PCA
pca = PCA(n_components = 1).fit(df_nu)

In [705]:
#Let's transform data frame 
df_nu = pd.DataFrame(pca.transform(df_nu))

In [706]:
#Let's look at columns
for i in df.columns:
    if i in useless:
        del df[i]

In [707]:
#Let's fit df to PCA
pca = PCA(n_components = 1).fit(df)

In [708]:
#Let's examine what the optimal number of components is 
n_components = 1
while pca.explained_variance_ratio_.cumsum()[-1] < 0.95:
    pca = PCA(n_components = n_components).fit(df)
    print(f'Components ==> {n_components} : {pca.explained_variance_ratio_.cumsum()}')
    print("======================================================================================")
    n_components += 1

Components ==> 1 : [0.39984749]
======================================================================================
Components ==> 2 : [0.39984749 0.59625908]
======================================================================================
Components ==> 3 : [0.39984749 0.59625908 0.7447267 ]
======================================================================================
Components ==> 4 : [0.39984749 0.59625908 0.7447267  0.87372012]
======================================================================================
Components ==> 5 : [0.39984749 0.59625908 0.7447267  0.87372012 0.90272513]
======================================================================================
Components ==> 6 : [0.39984749 0.59625908 0.7447267  0.87372012 0.90272513 0.92864786]
======================================================================================
Components ==> 7 : [0.39984749 0.59625908 0.7447267  0.87372012 0.90272513 0.92864786
 0.94527872]
======================================================================================
Components ==> 8 : [0.39984749 0.59625908 0.7447267  0.87372012 0.90272513 0.92864786
 0.94527872 0.95835671]
======================================================================================

In [709]:
#Let's fit df to PCA
pca = PCA(n_components = 8).fit(df)

In [710]:
#Let's transform data frame 
df = pd.DataFrame(pca.transform(df))

In [711]:
#Let's combine three data frame
df_general = pd.concat([df,df_nu,df_target],axis = 1 ,ignore_index = True)

In [712]:
#let's replace name of churn column
df_general.rename({9:'churn'} , axis = 1, inplace = True)

In [713]:
#Let's check correlations
for i in df_general:
    if i != 'churn':
        corr = df_general[i].corr(df_general['churn'])
        print(f'{i} & Churn  ==>  Correlation: {corr}')

0 & Churn  ==>  Correlation: 0.024156224790080012
1 & Churn  ==>  Correlation: 0.018147508998630553
2 & Churn  ==>  Correlation: 0.02325320604307005
3 & Churn  ==>  Correlation: 0.004194333634892127
4 & Churn  ==>  Correlation: 0.002519830390083649
5 & Churn  ==>  Correlation: 0.03429713973272642
6 & Churn  ==>  Correlation: 0.03382898185222722
7 & Churn  ==>  Correlation: 0.007661151310066963
8 & Churn  ==>  Correlation: -0.017057657373870015

In [714]:
#Let's use Random Forest Classifier  
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [715]:
#Let's define X and y values
y = df_general['churn']
X = df_general.drop(columns = 'churn')

In [716]:
#Let's divide data to train and test
X_train , X_test , y_train, y_test = train_test_split(X,y,random_state = 42,test_size = 0.2)

In [717]:
#Let's predict test values
rf = RandomForestClassifier().fit(X_train,y_train)
y_pred = rf.predict(X_test)

In [718]:
#Let's evaluate the model
rf.score(X_test,y_test)

0.5649122807017544

In [719]:
import xgboost as xgb 
model = xgb.XGBClassifier()

In [720]:
model.fit(X_train , y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [721]:
model.score(X_test,y_test)

0.5333333333333333

###  · HyperParameters

In [722]:
from sklearn.model_selection import RandomizedSearchCV

In [724]:
param_grid = {'n_estimators': np.arange(50,200,10),
             'learning_rate':np.logspace(-3,0,num = 10),
             'max_depth' : np.arange(3,8),
             'gamma':[0,0.1,0.2,0.3,0.4]}

In [725]:
random_search = RandomizedSearchCV(model, param_distributions= param_grid , n_iter = 50, scoring = 'accuracy' , n_jobs = -1 ,cv = 3 , random_state = 42 )

In [726]:
random_search.fit(X_train,y_train)

RandomizedSearchCV(cv=3,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric=None, feature_types=None,
                                           gamma=None, gpu_id=None,
                                           grow_policy=None,
                                           importance_type=None,
                                           interaction_constraints=None,
                                           learning_rate...
                                           predictor=None, random_state=None, ...),
                   n_iter=50, n_jobs=-1,
                   param_distributions={'gamma': [0, 0.1, 0.2, 0.3, 0.4],
                                        'learning_rate': array([0.001     , 0.00215443, 0.00464159, 0.01      , 0.02154435,
       0.04641589, 0.1       , 0.21544347, 0.46415888, 1.        ]),
                                        'max_depth': array([3, 4, 5, 6, 7]),
                                        'n_estimators': array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190])},
                   random_state=42, scoring='accuracy')

In [ ]:
random_search.best_params_

## · The End.